# Dockerfile

# 使用するベースイメージ
FROM php:8.2-fpm-alpine

# 必要なパッケージをインストール
RUN apk add --no-cache \
    git \
    unzip

# Composerをインストール
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# アプリケーションの作業ディレクトリを設定
WORKDIR /var/www/html

# アプリケーションのファイルをコピー
COPY . .

# Composerで依存関係をインストールし、アプリケーションをビルド
RUN composer install --no-dev --optimize-autoloader --prefer-dist
RUN docker-php-ext-install pdo pdo_mysql

# アプリケーションのファイルの所有者を設定
RUN chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache

# ポート80を公開
EXPOSE 80

# PHP-FPMを起動
CMD ["php-fpm"]
