version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        environment:
            APP_ENV: 'production'
            APP_DEBUG: 'false'
            APP_KEY: '${APP_KEY}'
            DB_CONNECTION: 'mysql'
            DB_HOST: 'mysql'
            DB_PORT: '3306'
            DB_DATABASE: '${DB_DATABASE}'
            DB_USERNAME: '${DB_USERNAME}'
            DB_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - '.:/var/www/html'
        depends_on:
            - mysql
        networks:
            - app-network
        restart: always

    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - 'mysql-data:/var/lib/mysql'
        networks:
            - app-network
        restart: always

    nginx:
        image: nginx:alpine
        ports:
            - '80:80'
        volumes:
            - './nginx/nginx.conf:/etc/nginx/nginx.conf'
            - '.:/var/www/html'
        depends_on:
            - app
        networks:
            - app-network
        restart: always

networks:
    app-network:
        driver: bridge

volumes:
    mysql-data:
        driver: local
