# Stage 1: Build Stage
FROM php:8.2-fpm-alpine as builder

WORKDIR /var/www/html

# Install dependencies
RUN apk add --no-cache \
    git \
    unzip

# Install Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Copy application files
COPY . .

# Install PHP dependencies
RUN composer install --no-dev --optimize-autoloader --prefer-dist

# Stage 2: Production Stage
FROM php:8.2-fpm-alpine

WORKDIR /var/www/html

# Copy application files from builder stage
COPY --from=builder /var/www/html /var/www/html

# Copy nginx config files if needed
# COPY ./nginx/nginx.conf /etc/nginx/nginx.conf

# Set up application permissions
RUN chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache

# Expose the port on which the app runs
EXPOSE 80

CMD ["php-fpm"]
